[2024-01-28T13:18:10.876+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summoner_id_dag.fetch_summoner_ids scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T13:18:10.882+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summoner_id_dag.fetch_summoner_ids scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T13:18:10.882+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-28T13:18:10.912+0100] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): fetch_summoner_ids> on 2024-01-27 00:00:00+00:00
[2024-01-28T13:18:10.917+0100] {standard_task_runner.py:60} INFO - Started process 6153 to run task
[2024-01-28T13:18:10.921+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'summoner_id_dag', 'fetch_summoner_ids', 'scheduled__2024-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/summoner_id_dag.py', '--cfg-path', '/tmp/tmp2fzjuud0']
[2024-01-28T13:18:10.926+0100] {standard_task_runner.py:88} INFO - Job 3: Subtask fetch_summoner_ids
[2024-01-28T13:18:11.012+0100] {task_command.py:423} INFO - Running <TaskInstance: summoner_id_dag.fetch_summoner_ids scheduled__2024-01-27T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-28T13:18:11.128+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nekruzk@3il.fr' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='summoner_id_dag' AIRFLOW_CTX_TASK_ID='fetch_summoner_ids' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T00:00:00+00:00'
[2024-01-28T13:18:11.130+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-28T13:18:11.131+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/hadoop/Desktop/projectBD/scripts/fetch_summoner_ids.py ']
[2024-01-28T13:18:11.142+0100] {subprocess.py:86} INFO - Output:
[2024-01-28T13:18:15.630+0100] {subprocess.py:93} INFO - put: Your endpoint configuration is wrong; For more details see:  http://wiki.apache.org/hadoop/UnsetHostnameOrPort
[2024-01-28T13:18:16.052+0100] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-28T13:18:16.085+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=summoner_id_dag, task_id=fetch_summoner_ids, execution_date=20240127T000000, start_date=20240128T121810, end_date=20240128T121816
[2024-01-28T13:18:16.137+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-28T13:18:16.144+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
