[2024-01-28T15:57:37.481+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summoner_id_dag.fetch_summoner_ids manual__2024-01-28T14:57:32.072638+00:00 [queued]>
[2024-01-28T15:57:37.490+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summoner_id_dag.fetch_summoner_ids manual__2024-01-28T14:57:32.072638+00:00 [queued]>
[2024-01-28T15:57:37.490+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-28T15:57:37.508+0100] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): fetch_summoner_ids> on 2024-01-28 14:57:32.072638+00:00
[2024-01-28T15:57:37.512+0100] {standard_task_runner.py:60} INFO - Started process 17565 to run task
[2024-01-28T15:57:37.515+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'summoner_id_dag', 'fetch_summoner_ids', 'manual__2024-01-28T14:57:32.072638+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/summoner_id_dag.py', '--cfg-path', '/tmp/tmpukorfbj6']
[2024-01-28T15:57:37.520+0100] {standard_task_runner.py:88} INFO - Job 8: Subtask fetch_summoner_ids
[2024-01-28T15:57:37.571+0100] {task_command.py:423} INFO - Running <TaskInstance: summoner_id_dag.fetch_summoner_ids manual__2024-01-28T14:57:32.072638+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-28T15:57:37.627+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nekruzk@3il.fr' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='summoner_id_dag' AIRFLOW_CTX_TASK_ID='fetch_summoner_ids' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T14:57:32.072638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-28T14:57:32.072638+00:00'
[2024-01-28T15:57:37.631+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-28T15:57:37.632+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/hadoop/Desktop/projectBD/scripts/fetch_summoner_ids.py ']
[2024-01-28T15:57:37.639+0100] {subprocess.py:86} INFO - Output:
[2024-01-28T15:57:43.761+0100] {subprocess.py:93} INFO - API call failed for Tarelcat: Status Code 403, Response {"status":{"message":"Forbidden","status_code":403}}
[2024-01-28T15:57:43.762+0100] {subprocess.py:93} INFO - No data fetched for summoner: Tarelcat
[2024-01-28T15:57:43.762+0100] {subprocess.py:93} INFO - API call failed for Kawozz: Status Code 403, Response {"status":{"message":"Forbidden","status_code":403}}
[2024-01-28T15:57:43.762+0100] {subprocess.py:93} INFO - No data fetched for summoner: Kawozz
[2024-01-28T15:57:43.762+0100] {subprocess.py:93} INFO - API call failed for Saken: Status Code 403, Response {"status":{"message":"Forbidden","status_code":403}}
[2024-01-28T15:57:43.762+0100] {subprocess.py:93} INFO - No data fetched for summoner: Saken
[2024-01-28T15:57:43.762+0100] {subprocess.py:93} INFO - No new data to update.
[2024-01-28T15:57:43.777+0100] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-28T15:57:43.803+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=summoner_id_dag, task_id=fetch_summoner_ids, execution_date=20240128T145732, start_date=20240128T145737, end_date=20240128T145743
[2024-01-28T15:57:43.843+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-28T15:57:43.849+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
