[2024-01-29T00:01:04.099+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: match_id_dag.fetch_match_ids manual__2024-01-28T23:01:02.564845+00:00 [queued]>
[2024-01-29T00:01:04.103+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: match_id_dag.fetch_match_ids manual__2024-01-28T23:01:02.564845+00:00 [queued]>
[2024-01-29T00:01:04.103+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-29T00:01:04.121+0100] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): fetch_match_ids> on 2024-01-28 23:01:02.564845+00:00
[2024-01-29T00:01:04.125+0100] {standard_task_runner.py:60} INFO - Started process 12320 to run task
[2024-01-29T00:01:04.127+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'match_id_dag', 'fetch_match_ids', 'manual__2024-01-28T23:01:02.564845+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/match_id_dag.py', '--cfg-path', '/tmp/tmp0ypk5du3']
[2024-01-29T00:01:04.129+0100] {standard_task_runner.py:88} INFO - Job 25: Subtask fetch_match_ids
[2024-01-29T00:01:04.168+0100] {task_command.py:423} INFO - Running <TaskInstance: match_id_dag.fetch_match_ids manual__2024-01-28T23:01:02.564845+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-29T00:01:04.254+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='irachide1@gmail.com' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='match_id_dag' AIRFLOW_CTX_TASK_ID='fetch_match_ids' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T23:01:02.564845+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-28T23:01:02.564845+00:00'
[2024-01-29T00:01:04.255+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-29T00:01:04.256+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/hadoop/Desktop/projectBD/scripts/fetch_match_ids.py ']
[2024-01-29T00:01:04.262+0100] {subprocess.py:86} INFO - Output:
[2024-01-29T00:01:09.542+0100] {subprocess.py:93} INFO - API call failed: Status Code 403, Response {"status":{"message":"Forbidden","status_code":403}}
[2024-01-29T00:01:09.542+0100] {subprocess.py:93} INFO - Failed to fetch match IDs for Tarelcat
[2024-01-29T00:01:09.542+0100] {subprocess.py:93} INFO - API call failed: Status Code 403, Response {"status":{"message":"Forbidden","status_code":403}}
[2024-01-29T00:01:09.543+0100] {subprocess.py:93} INFO - Failed to fetch match IDs for Kawozz
[2024-01-29T00:01:09.543+0100] {subprocess.py:93} INFO - API call failed: Status Code 403, Response {"status":{"message":"Forbidden","status_code":403}}
[2024-01-29T00:01:09.543+0100] {subprocess.py:93} INFO - Failed to fetch match IDs for Saken
[2024-01-29T00:01:09.543+0100] {subprocess.py:93} INFO - Failed to fetch match IDs for all summoners. Exiting.
[2024-01-29T00:01:09.562+0100] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-29T00:01:09.572+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/hadoop/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-29T00:01:09.582+0100] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=match_id_dag, task_id=fetch_match_ids, execution_date=20240128T230102, start_date=20240128T230104, end_date=20240128T230109
[2024-01-29T00:01:09.609+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task fetch_match_ids (Bash command failed. The command returned a non-zero exit code 1.; 12320)
[2024-01-29T00:01:09.644+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-29T00:01:09.652+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
