[2024-01-29T01:11:06.391+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: match_histories_dag.fetch_match_histories manual__2024-01-29T00:11:03.180969+00:00 [queued]>
[2024-01-29T01:11:06.400+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: match_histories_dag.fetch_match_histories manual__2024-01-29T00:11:03.180969+00:00 [queued]>
[2024-01-29T01:11:06.400+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-29T01:11:06.439+0100] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): fetch_match_histories> on 2024-01-29 00:11:03.180969+00:00
[2024-01-29T01:11:06.449+0100] {standard_task_runner.py:60} INFO - Started process 21762 to run task
[2024-01-29T01:11:06.452+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'match_histories_dag', 'fetch_match_histories', 'manual__2024-01-29T00:11:03.180969+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/match_histories_dag.py', '--cfg-path', '/tmp/tmp_urq365i']
[2024-01-29T01:11:06.454+0100] {standard_task_runner.py:88} INFO - Job 57: Subtask fetch_match_histories
[2024-01-29T01:11:06.508+0100] {task_command.py:423} INFO - Running <TaskInstance: match_histories_dag.fetch_match_histories manual__2024-01-29T00:11:03.180969+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-29T01:11:06.613+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='irachide1@gmail.com' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='match_histories_dag' AIRFLOW_CTX_TASK_ID='fetch_match_histories' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T00:11:03.180969+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T00:11:03.180969+00:00'
[2024-01-29T01:11:06.615+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-29T01:11:06.615+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/hadoop/Desktop/projectBD/scripts/fetch_match_histories.py ']
[2024-01-29T01:11:06.622+0100] {subprocess.py:86} INFO - Output:
[2024-01-29T01:12:45.048+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Kawozz/EUW1_6582663425.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Kawozz/EUW1_6582606609.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Kawozz/EUW1_6581795566.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Kawozz/EUW1_6581740231.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Kawozz/EUW1_6580143125.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Saken/EUW1_6739785061.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Saken/EUW1_6738385382.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Saken/EUW1_6738349537.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Saken/EUW1_6738285599.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Saken/EUW1_6732783419.json': File exists
[2024-01-29T01:12:45.049+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Tarelcat/EUW1_6739442502.json': File exists
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Tarelcat/EUW1_6739410670.json': File exists
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Tarelcat/EUW1_6708297963.json': File exists
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Tarelcat/EUW1_6708267139.json': File exists
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - Error uploading file to HDFS: put: `/user/hadoop/lol/raw/match_histories/Tarelcat/EUW1_6708242857.json': File exists
[2024-01-29T01:12:45.050+0100] {subprocess.py:93} INFO - 
[2024-01-29T01:12:45.089+0100] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-29T01:12:45.144+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=match_histories_dag, task_id=fetch_match_histories, execution_date=20240129T001103, start_date=20240129T001106, end_date=20240129T001245
[2024-01-29T01:12:45.231+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-29T01:12:45.266+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
